// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTy7R8Rx6IKbwq8BPf25MG1AhjZ0sIyo',
    appId: '1:32267600940:web:710f1ad841129f72bdfd89',
    messagingSenderId: '32267600940',
    projectId: 'graduationproject-504215',
    authDomain: 'graduationproject-504215.firebaseapp.com',
    storageBucket: 'graduationproject-504215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JgrXcdHaJALWgFzsTwD7Ti3TxpTU9dM',
    appId: '1:32267600940:android:df756ef18cf4e3a5bdfd89',
    messagingSenderId: '32267600940',
    projectId: 'graduationproject-504215',
    storageBucket: 'graduationproject-504215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXRyB6t-e7Gr0xCKPMu2ypOr2K1r-5N4',
    appId: '1:32267600940:ios:0641cca6c76f2ef0bdfd89',
    messagingSenderId: '32267600940',
    projectId: 'graduationproject-504215',
    storageBucket: 'graduationproject-504215.firebasestorage.app',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXRyB6t-e7Gr0xCKPMu2ypOr2K1r-5N4',
    appId: '1:32267600940:ios:0641cca6c76f2ef0bdfd89',
    messagingSenderId: '32267600940',
    projectId: 'graduationproject-504215',
    storageBucket: 'graduationproject-504215.firebasestorage.app',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTy7R8Rx6IKbwq8BPf25MG1AhjZ0sIyo',
    appId: '1:32267600940:web:2d400ffedf946e7abdfd89',
    messagingSenderId: '32267600940',
    projectId: 'graduationproject-504215',
    authDomain: 'graduationproject-504215.firebaseapp.com',
    storageBucket: 'graduationproject-504215.firebasestorage.app',
  );
}
